{% set version = '9.0.0' %}

package:
  name: libglu
  version: {{ version }}

source:
  url: ftp://ftp.freedesktop.org/pub/mesa/glu/glu-{{ version }}.tar.gz
  sha256: 4387476a1933f36fec1531178ea204057bbeb04cc2d8396c9ea32720a1f7e264
  patches:
    - 001-update-config-guess.patch

build:
  number: 1004
  skip: True  # [win or osx]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    # These dependencies are only for cos7 platforms
    - {{ cdt('mesa-libglapi') }}     # [linux & (ppc64le | aarch64)]
    - {{ cdt('mesa-khr-devel') }}    # [linux & (ppc64le | aarch64)]
    - pkg-config                    # [unix]
    - make                          # [unix]
  host:
    - xorg-libx11                        # [linux]
    - xorg-fixesproto                    # [linux]
    - xorg-xproto                        # [linux]
    - xorg-kbproto                       # [linux]
    - xorg-xextproto                     # [linux]
    - xorg-damageproto                   # [linux]
    - xorg-xf86vidmodeproto              # [linux]
    - xorg-libxext                       # [linux]
    - xorg-libxdamage                    # [linux]
    - xorg-libxxf86vm                    # [linux]
    - libxcb                             # [linux]
    # These dependencies are only for cos7 platforms
    - xorg-libxau  # [linux & (ppc64le | aarch64)]
    - xorg-libxdmcp  # [linux & (ppc64le | aarch64)]

test:
  commands:
    - test -f ${PREFIX}/lib/libGLU.a  # [not win]
    - test -f ${PREFIX}/lib/libGLU${SHLIB_EXT}  # [not win]

about:
  home: http://www.mesa3d.org/glu.html
  license: SGI-2
  summary: Mesa OpenGL utility library (GLU)

extra:
  recipe-maintainers:
    - bgruening
