{% set version = '9.0.0' %}

package:
  name: libglu
  version: {{ version }}

source:
  url: ftp://ftp.freedesktop.org/pub/mesa/glu/glu-{{ version }}.tar.gz
  sha256: 4387476a1933f36fec1531178ea204057bbeb04cc2d8396c9ea32720a1f7e264

build:
  number: 1000
  skip: True  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    # These dependencies are only for cos7 platforms
    - {{ cdt('libglvnd-glx') }}          # [linux & (ppc64le | aarch64)]
    - {{ cdt('libglvnd') }}              # [linux & (ppc64le | aarch64)]
    - {{ cdt('libxshmfence-devel') }}    # [linux & (ppc64le | aarch64)]
    - {{ cdt('mesa-khr-devel') }}        # [linux & (ppc64le | aarch64)]
    - pkg-config                    # [unix]
    - make                          # [unix]
    - autoconf                      # [unix]
    - automake                      # [unix]
    - gettext                       # [unix]
    - libtool                       # [unix]

test:
  commands:
    - test -f ${PREFIX}/lib/libGLU.a  # [not win]
    - test -f ${PREFIX}/lib/libGLU${SHLIB_EXT}  # [not win]

about:
  home: http://www.mesa3d.org/glu.html
  license: SGI-2
  summary: Mesa OpenGL utility library (GLU)

extra:
  recipe-maintainers:
    - bgruening
