{% set version = '9.0.3' %}

package:
  name: libglu
  version: {{ version }}

source:
  url: https://gitlab.freedesktop.org/mesa/glu/-/archive/glu-{{ version }}/glu-glu-{{ version }}.tar.bz2
  sha256: 38044ee4f255578165a54eaeb089b67fb64f7f7c0ce5fa690cd47c9df10b263c

build:
  number: 1
  skip: True  # [win or osx]
  run_exports:
    - {{ pin_subpackage('libglu', max_pin='x.x') }}
  ignore_run_exports_from:
    # We use libgl-devel only for GL.h and we do not link it, so we ignore the run_exports on libgl
    # as we depend on libopengl instead on Linux
    - libgl-devel                        # [linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - pkg-config
    - ninja
    - meson
  host:
    - libgl-devel                        # [linux]
    - libopengl-devel                    # [linux]

test:
  commands:
    - test -f ${PREFIX}/lib/libGLU.a  # [not win]
    - test -f ${PREFIX}/lib/libGLU${SHLIB_EXT}  # [not win]

about:
  home: http://www.mesa3d.org/glu.html
  license: SGI-B-2.0
  summary: Mesa OpenGL utility library (GLU)
  dev_url: https://gitlab.freedesktop.org/mesa/glu

extra:
  recipe-maintainers:
    - bgruening
    - hmaarrfk
    - traversaro
